### PR TITLE
infocommand.py Created by Myst | Peace

### PR DESCRIPTION
**Pull request by TrueMyst**
Uhh! Some Amazing Info Commands for your Bot, which are really Helpful! All of the Commands are Made by me! If Something is Wrong Feel Free to DM me in Discord Myst | 죽음#9105

### CODE REVIEW

**Review by BobDotCom — CHANGES_REQUESTED** [review]
There are some PEP8 inconsistencies in this code. Check out https://github.com/The-Coding-Academy/Community-Bin/runs/2163835631?check_suite_focus=true, and once you fix the issues there I will be able to merge this.

**Comment by BobDotCom** [comment]
@MystYT-21 Please make those changes or I won't be able to merge this

**Review by BobDotCom — CHANGES_REQUESTED** [review]
Neither of the files is explicitly bad, but they are both PEP8 inconsistent. Please review the code style guidelines for this repo and update this PR.

**Comment by MystYT-21** [comment]
Delete it! Im done! ;--;

**Comment by DriftAsimov** [comment]
Typo in line **153**
* Change `titile` to `title`

**Comment by BobDotCom** [comment]
If someone reformats this code, it may be accepted and merged. Please do so or this pull request will be closed

**Pull request closed without merging**
