### PR TITLE
Added chainging-status.js

### PR DESCRIPTION
**Pull request by TasfiqulTapu**
An example on hoe to use .env file to store config in enviroment.

### CODE REVIEW

**Review by BobDotCom — CHANGES_REQUESTED** [review]
```
[warn] javascript/discord.js/env-example/README.md
[warn] javascript/discord.js/env-example/server.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```
Please run prettier to format your code. Once it passes the checks I can merge it

**Review by BobDotCom — CHANGES_REQUESTED** [review]
https://github.com/The-Coding-Academy/Community-Bin/runs/2168501168?check_suite_focus=true try to fix these errors

**Review by BobDotCom — CHANGES_REQUESTED** [review]
some errors still, it says server.js is failing checks

**Comment by TasfiqulTapu** [comment]
env-example/server.js was failing. I will re-upload it later

**Review by BobDotCom — APPROVED** [review]
k

**Pull request merged**
